services:

  # Servicio para la base de datos (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: WPDB
      MYSQL_USER: adminwp
      MYSQL_PASSWORD: +Adminwp2024
      MYSQL_ROOT_PASSWORD: +Root2024
    volumes:
      - wp-data:/var/lib/mysql
    networks:
      - wp-network

  # Servicio para WordPress
  wordpress:
    image: wordpress:latest
    container_name: wp-container
    restart: always
    ports:
      - 6001:80  # Exponer el puerto 80 de WordPress en el puerto 6001 del host
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: adminwp
      WORDPRESS_DB_PASSWORD: +Adminwp2024
      WORDPRESS_DB_NAME: WPDB
    volumes:
      - wp-app:/var/www/html      
    depends_on:
      - db
    networks:
      - wp-network

  # Servicio para phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    restart: always
    ports:
      - 6002:80  # Exponer phpMyAdmin en el puerto 6002 del host
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: +Root2024  # Contraseña de root de MySQL
    depends_on:
      - db
    networks:
      - wp-network

# Definición de la red
networks:
  wp-network:

# Definición de la red
volumes:
  wp-data:
  wp-app:
